name: Build Docker and Deploy

on:
    push: 
        branches: ['main']
    pull_request: 
        branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Create .env file from secrets
        run: |
          echo "VITE_DEV=${{ secrets.DEV }}" >> .env.local
          echo "VITE_API_URL=${{ secrets.API_URL }}" >> .env.local
         

      - name: Build Docker image
        run: docker build -t solvld/emp:latest .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: docker push solvld/emp:latest

  deploy:
    if: github.event_name == 'push'
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull solvld/emp:latest
            docker stop emp || true
            docker rm emp || true
            docker run -d \
            --name emp \
            -p 80:80 \
            solvld/emp:latest